name: Pull Request 템플릿

body:
  - type: markdown
    attributes:
      value: |
        # Pull Request 템플릿

        아래 항목을 작성하여 Pull Request를 제출해주세요.

  - type: input
    id: title
    attributes:
      label: 제목
      description: 변경 사항의 요약을 간단히 작성해주세요.
      placeholder: "예: 로그인 기능 개선"

  - type: textarea
    id: description
    attributes:
      label: 변경 사항 설명
      description: 이 PR에서 수행한 주요 변경 사항을 설명해주세요.
      placeholder: |
        - 변경 1
        - 변경 2

  - type: dropdown
    id: related_issue
    attributes:
      label: 관련 이슈
      description: 이 PR이 해결하려는 관련 이슈를 선택해주세요.
      options:
        - 없음
        - Bug Fix (버그 수정)
        - Feature Request (기능 요청)
        - Documentation Update (문서 업데이트)
        - 기타

  - type: textarea
    id: test_plan
    attributes:
      label: 테스트 계획
      description: 이 변경 사항이 올바르게 작동하는지 테스트한 방법을 작성해주세요.
      placeholder: "예: 테스트 케이스 추가, 수동 테스트 실행 등"
