name: 오류 신고
description: 오류를 신고하여 프로그래머를 도와주세요.
title: "[Bug] 제목을 입력하세요"
labels: 
  - bug
assignees:
  - 202420505
body:
  - type: markdown
    attributes:
      value: |
        **버그에 대한 설명을 구체적으로 작성해 주세요.**

  - type: textarea
    id: description
    attributes:
      label: 버그 설명
      description: 버그에 대한 자세한 내용을 적어 주세요.
      placeholder: 이곳에 버그 설명을 입력하세요.

  - type: markdown
    attributes:
      value: |
        **버그가 생성된 방법을 구체적으로 설명해 주세요.**

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: 버그 생성된 방법
      description: 버그를 재현할 수 있는 단계를 순서대로 작성해 주세요.
      placeholder: 예: 1. Go to '...' 2. Click on '...' 3. Scroll down to '...' 4. See error

  - type: input
    id: expected_behavior
    attributes:
      label: 원하는 행동
      description: 이 버그가 어떻게 해결되길 원하시는지 적어 주세요.
      placeholder: 이곳에 원하는 행동을 입력하세요.

  - type: textarea
    id: additional_context
    attributes:
      label: 기타 사항
      description: 추가적으로 알리고 싶은 내용을 입력해 주세요.
      placeholder: 이곳에 기타 사항을 입력하세요.
