name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치 푸시 시 실행 (필요에 따라 변경)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js (optional, if your project requires it)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build project
      run: |
        npm install  # 필요한 경우
        npm run build  # output 폴더를 생성하는 명령어

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: image  # 배포할 폴더 경로
