name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload `v4/` directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
